//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual_NXC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visual_NXC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _enum {
            get {
                object obj = ResourceManager.GetObject("_enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _struct {
            get {
                object obj = ResourceManager.GetObject("_struct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chevronDown {
            get {
                object obj = ResourceManager.GetObject("chevronDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chevronUp {
            get {
                object obj = ResourceManager.GetObject("chevronUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs
        ///sign
        ///SetSensor
        ///SetSensorType
        ///SetSensorMode
        ///ClearSensor
        ///SensorValue
        ///SensorType
        ///SensorMode
        ///SensorValueBool
        ///SensorValueRaw
        ///SetSensorLowerLimit
        ///SetSensorUpperLimit
        ///SetSensorHysteresis
        ///CalibrateSensor
        ///SetOutput
        ///SetDirection
        ///SetPower
        ///OutputStatus
        ///On
        ///Off
        ///Float
        ///Fwd
        ///Rev
        ///Toggle
        ///OnFwd
        ///OnRev
        ///OnFor
        ///SetGlobalOutput
        ///SetGlobalDirection
        ///SetMaxPower
        ///EnableOutput
        ///DisableOutput
        ///InvertOutput
        ///ObvertOutput
        ///GlobalOutputStatus
        ///PlaySound
        ///PlayTone
        ///MuteSound
        ///UnmuteSound
        ///ClearSound
        ///SelectSou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commandsDefault {
            get {
                return ResourceManager.GetString("commandsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SENSOR_CFG
        ///ACCL_CMD_RESET_CAL
        ///ACCL_CMD_X_CAL
        ///ACCL_CMD_X_CAL_END
        ///ACCL_CMD_Y_CAL
        ///ACCL_CMD_Y_CAL_END
        ///ACCL_CMD_Z_CAL
        ///ACCL_CMD_Z_CAL_END
        ///ACCL_REG_SENS_LVL
        ///ACCL_REG_X_ACCEL
        ///ACCL_REG_X_OFFSET
        ///ACCL_REG_X_RANGE
        ///ACCL_REG_X_TILT
        ///ACCL_REG_Y_ACCEL
        ///ACCL_REG_Y_OFFSET
        ///ACCL_REG_Y_RANGE
        ///ACCL_REG_Y_TILT
        ///ACCL_REG_Z_ACCEL
        ///ACCL_REG_Z_OFFSET
        ///ACCL_REG_Z_RANGE
        ///ACCL_REG_Z_TILT
        ///ACCL_SENSITIVITY_LEVEL_1
        ///ACCL_SENSITIVITY_LEVEL_2
        ///ACCL_SENSITIVITY_LEVEL_3
        ///ACCL_SENSITIVITY_LEVEL_4
        ///Acos
        ///AcosD
        ///ActualSpeedField
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contantsDefault {
            get {
                return ResourceManager.GetString("contantsDefault", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap control_270 {
            get {
                object obj = ResourceManager.GetObject("control_270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_270_disabled {
            get {
                object obj = ResourceManager.GetObject("control_270_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross_transparent {
            get {
                object obj = ResourceManager.GetObject("cross_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cursor_dark {
            get {
                object obj = ResourceManager.GetObject("cursor_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cursor_transparent {
            get {
                object obj = ResourceManager.GetObject("cursor_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dock_left {
            get {
                object obj = ResourceManager.GetObject("dock_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dock_left_highlight {
            get {
                object obj = ResourceManager.GetObject("dock_left_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dock_right {
            get {
                object obj = ResourceManager.GetObject("dock_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dock_right_highlight {
            get {
                object obj = ResourceManager.GetObject("dock_right_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eraser_crosshairs {
            get {
                object obj = ResourceManager.GetObject("eraser_crosshairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eraser_transparent {
            get {
                object obj = ResourceManager.GetObject("eraser_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand___gloved {
            get {
                object obj = ResourceManager.GetObject("hand___gloved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand___gloved_transparent {
            get {
                object obj = ResourceManager.GetObject("hand___gloved_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HandClosed {
            get {
                object obj = ResourceManager.GetObject("HandClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HandOpen {
            get {
                object obj = ResourceManager.GetObject("HandOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __FLTRETVAL__
        ///__RETURN__
        ///__RETURNF__
        ///__RETURNS__
        ///__RETURNU__
        ///__RETVAL__
        ///__STRRETVAL__
        ///__STRBUFFER__
        ///__STRTMPBUFFER__
        ///__TMPBYTE__
        ///__TMPFLOAT__
        ///__TMPLONG__
        ///__TMPULONG__
        ///__TMPWORD__
        ///asm
        ///bool
        ///break
        ///byte
        ///case
        ///char
        ///const
        ///continue
        ///default
        ///do
        ///else
        ///enum
        ///false
        ///float
        ///for
        ///goto
        ///if
        ///inline
        ///int
        ///long
        ///mutex
        ///priority
        ///repeat
        ///return
        ///safecall
        ///short
        ///start
        ///stop
        ///string
        ///struct
        ///sub
        ///switch
        ///task
        ///true
        ///typedef
        ///unsigned
        ///until
        ///void
        ///while.
        /// </summary>
        internal static string keywordsDefault {
            get {
                return ResourceManager.GetString("keywordsDefault", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap layer_resize {
            get {
                object obj = ResourceManager.GetObject("layer-resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_resize_actual {
            get {
                object obj = ResourceManager.GetObject("layer-resize-actual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_resize_actual_transparent {
            get {
                object obj = ResourceManager.GetObject("layer-resize-actual_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap method {
            get {
                object obj = ResourceManager.GetObject("method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plus_small {
            get {
                object obj = ResourceManager.GetObject("plus_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pop_out {
            get {
                object obj = ResourceManager.GetObject("pop_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pop_out_highlight {
            get {
                object obj = ResourceManager.GetObject("pop_out_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap receipts_text {
            get {
                object obj = ResourceManager.GetObject("receipts_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabDeselected {
            get {
                object obj = ResourceManager.GetObject("TabDeselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabHover {
            get {
                object obj = ResourceManager.GetObject("TabHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabSelected {
            get {
                object obj = ResourceManager.GetObject("TabSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thread {
            get {
                object obj = ResourceManager.GetObject("thread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileBg {
            get {
                object obj = ResourceManager.GetObject("TileBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileBg_HalfOpac {
            get {
                object obj = ResourceManager.GetObject("TileBg_HalfOpac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_click {
            get {
                object obj = ResourceManager.GetObject("x_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_hover {
            get {
                object obj = ResourceManager.GetObject("x_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
